version: "2"

services:
  db:
    container_name: voting-postgres-db
    build:
      context: ./postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      vote_app:
    volumes:
      - vote_postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  factomd:
    container_name: voting-factomd
#    image: factominc/factomd:v5.1.0-alpine
    build:
       context: .
       dockerfile: Dockerfile.factomd
    networks:
      vote_app:
#    depends_on:
#        - postgres_db
    ports:
        - "8090:8090"
        - "8088:8088"
    volumes:
      - vote_factomd_volume:/root/.factom/
    env_file:
      - factomd.env


  scraper:
    container_name: voting-scraper
    build:
       context: .
       dockerfile: Dockerfile.scraper
    networks:
      vote_app:
    ports:
        - "6061:6060"
    depends_on:
        - db
        - factomd
    env_file:
      - factomd.env

  apiserver:
    container_name: voting-apiserver
    build:
       context: .
       dockerfile: Dockerfile.apiserver
    networks:
      vote_app:
    ports:
        - "80:8080"
    depends_on:
        - db
        - factomd
    env_file:
      - factomd.env


networks:
  vote_app:

volumes:
  vote_postgres_volume:
  vote_factomd_volume:
  vote_walletd_volume:
